
version: '3.8'
services:
  db:
    image: mongo
    volumes:
    - ./data/db:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: ${MONGODB_URL}
      jwt_secret: ${JWT_SECRET}
    depends_on:
      - db

